### ISSUE TITLE
suport Another Quick Switcher

### ISSUE THREAD

**Issue by calmwaves111** [RyotaUshio/obsidian-enhanced-link-suggestions#8]
In fact, I use this plugin ： https://github.com/tadashi-aikawa/obsidian-another-quick-switcher

**Comment by RyotaUshio** [comment]
Only the dev of another quick switcher can implement its quick preview support [using the API](https://github.com/RyotaUshio/obsidian-quick-preview?tab=readme-ov-file#using-the-api). Please (politely) contact him instead
